### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by kanlukasz** [pwarchol/vscode-php-file-link#1]
Hello _[lub cześć,  jak coś to możemy pisać też po polsku 😉  ]_

I started testing your add-on.
For the first tests, I used a fresh instance of Wordpress

The environment in which I test it is:
- Win10 20H2
- VSCode 1.55.2 (clean and fresh portable version)
- VSCode settings: default
- Add-on settings: default

_(I will test this on Ubuntu WSL2 in the future as well)_

### Below are some screens with missing links:

`wp-load.php`
![image](https://user-images.githubusercontent.com/30685349/116116929-fede2a80-a6bb-11eb-9a8a-c33deb0825ac.png)

`wp-admin\nav-menus.php`
![image](https://user-images.githubusercontent.com/30685349/116116994-0f8ea080-a6bc-11eb-82a7-ee8fc5fcb845.png)

`wp-content\themes\twentytwenty\functions.php`
![image](https://user-images.githubusercontent.com/30685349/116117042-1d442600-a6bc-11eb-9b4f-1f8ade25f574.png)

`wp-content\themes\twentysixteen\functions.php`
![image](https://user-images.githubusercontent.com/30685349/116117117-2cc36f00-a6bc-11eb-9eb1-95a726a5bd39.png)

**Comment by pwarchol** [comment]
Cześć,

Sprawa jest trochę skomplikowana, nie bez powodu PHP IntelliSense do vscode
nie ma takiej opcji, bo ona generalnie trochę nie ma sensu z racji takiej
że nigdy nie zadziała w 100% :)
Wszystkie przykłady które podałeś mają ten sam problem, mianowicie jest
więcej niż jeden pasujący plik.
Przykładowo plików /inc/back-compat.php jest 7.
Zastanawiałem się nawet czy nie mogę parsować całej aplikacji żeby
rozwiązywać pełne ścieżki (np. funkcje get_template_directory() czy stałe
typu ABSPATH)
Ale nie ma to żadnego sensu bo te stałe czy funkcje mogą polegać na
źródłach zewnętrznych np. pobierać je z bazy.

Wydaje mi się że mogę jeszcze poprawić dwie kwestie:
1. parsowanie / rozpoznawanie predefiniowanych stałych typu __DIR__ to by
pomogło w  wp-admin\nav-menus.php
2. linkować wszystko a po kliknięciu takich których jest więcej pokazywać
listę:

[image: back-compat.png]

Punkt 2 jest już in progress więc pewnie do niedzieli wleci nowa wersja :)

Dzięki za zgłoszenie i chęci :)

PS. Linkowanie pliku który jest najbliżej lub posiada ten sam nadrzędny
katalog co obecnie otwarty plik, może i by było skuteczne w 90%, ale te 10%
dostawało by niesamowitej piany, jak otwierało by się nie to co trzeba :D

pon., 26 kwi 2021 o 18:23 kanlukasz ***@***.***> napisał(a):

**Comment by pwarchol** [comment]
Cześć,

Sprawa jest trochę skomplikowana, nie bez powodu PHP IntelliSense do vscode nie ma takiej opcji, bo ona generalnie trochę nie ma sensu z racji takiej że nigdy nie zadziała w 100% :)
Wszystkie przykłady które podałeś mają ten sam problem, mianowicie jest więcej niż jeden pasujący plik.
Przykładowo plików /inc/back-compat.php jest 7.
Zastanawiałem się nawet czy nie mogę parsować całej aplikacji żeby rozwiązywać pełne ścieżki (np. funkcje get_template_directory() czy stałe typu ABSPATH)
Ale nie ma to żadnego sensu bo te stałe czy funkcje mogą polegać na źródłach zewnętrznych np. pobierać je z bazy.

Wydaje mi się że mogę jeszcze poprawić dwie kwestie:
1. parsowanie / rozpoznawanie predefiniowanych stałych typu __DIR__ to by pomogło w  wp-admin\nav-menus.php
2. linkować wszystko a po kliknięciu takich których jest więcej pokazywać listę:

![back-compat](https://user-images.githubusercontent.com/39327615/116142703-85096980-a6da-11eb-8800-345fb25b61cf.png)

Punkt 2 jest już in progress więc pewnie do niedzieli wleci nowa wersja :)

Dzięki za zgłoszenie i chęci :)

PS. Linkowanie pliku który jest najbliżej lub posiada ten sam nadrzędny katalog co obecnie otwarty plik, może i by było skuteczne w 90%, ale te 10% nie było by zadowolone :D

**Comment by kanlukasz** [comment]
Dzięki za odp. Te usprawnienia brzmią okej, także czekam na kolejny release i będę testował :-)

**Comment by pwarchol** [comment]
@kanlukasz Właśnie opublikowałem nową wersję. Linki juz powinny się pojawiać do wszystkich plików które istnieją czyli będzie brakować linkowania np. do wp-config.php (domyślnie w repo wordpressa nie ma takiego pliku).

**Comment by kanlukasz** [comment]
Cześć,

Zrobiłem testy, teraz działa super!

To co jeszcze wychwyciłem to kwestia sposobu otwierania listy dla duplikatów (np. jak utworzę i zduplikuje plik wp-config)
W tamtej wtyczce `Open file From Path` działa to chyba nieco bardziej intuicyjnie

Poniżej podsyłam różnicę na screenach:

## Sposób otwierania listy duplikatów we wtyczce `Open file From Path`
![image](https://user-images.githubusercontent.com/30685349/117112212-0327d900-ad89-11eb-8a9d-d476f2964368.png)
![image](https://user-images.githubusercontent.com/30685349/117112237-0c18aa80-ad89-11eb-8d0b-2fd2c75c6be8.png)

## Sposób otwierania listy duplikatów w Twojej wtyczce `PHP File Link`
![image](https://user-images.githubusercontent.com/30685349/117112297-2783b580-ad89-11eb-9c72-58a5eb30de35.png)
![image](https://user-images.githubusercontent.com/30685349/117112315-2eaac380-ad89-11eb-8a99-f6e397fa831a.png)

Co o tym myślisz :) ?

**Comment by pwarchol** [comment]
Masz rację, zaplanuję sobie taką modyfikację.
Dam znać, dzięki.

**Comment by pwarchol** [comment]
@kanlukasz v0.3.0 opublikowana, zawiera modyfikacje listy duplikatów
