### ISSUE TITLE
Can you add to VSCodium?

### ISSUE THREAD

**Issue by bielpons91** [pwarchol/vscode-php-file-link#10]
Hi, I really liked your work, I have tested it in Visual Studio Code and it works very well, would it be possible to install it from VSCodium?

Best regards

**Comment by pwarchol** [comment]
Hi, extension is now available in [open-vsx](https://open-vsx.org/extension/pwarchol/vscode-php-file-link).
Now you can install this extension from VSCodium.

**Comment by bielpons91** [comment]
Thank you very much!
