### ISSUE TITLE
Unable to make it work with different file extensions

### ISSUE THREAD

**Issue by ssbarnea** [pwarchol/vscode-php-file-link#11]
I tried to enable it for `py` files where I have a simple line like below:
```
FILE = "examples/playbooks/with-skip-tag-id.yml"
```

I tried to use Cmd+Click to hover over it but it did not work, even if the file path is correct.

PS. Yes, I did configure the extra file extensions.

**Comment by pwarchol** [comment]
Hi, extension can assign links only for php files, thats why this is "PHP File Link".
supportedExtensions settings declares only which file can be linked inside php file.

**Comment by pwarchol** [comment]
This extension parses php to AST node tree to detect `__DIR__` constant or `dirname(__FILE__)` inside php.

**Comment by ssbarnea** [comment]
@pwarchol Quoting from readme: `"default": ["php","ini","log"]`... somehow I am kinda sure that the last two extensions are non php code ;)

I imagined that the extension was able to identify strings that look like filenames and use them, regarding the specific language of the document.
