### ISSUE TITLE
Invalid linking for a directory that does not exist

### ISSUE THREAD

**Issue by kanlukasz** [pwarchol/vscode-php-file-link#3]
I jeszcze jedną rzecz wyłapałem.

Jeżeli masz dowolny plik gdzieś w projekcie, to nawet jak podasz nieistniejącą ścieżkę do tego pliku, to i tak go otwiera.
Chyba nie powinno, no bo w sumie pod tą ścieżką ten plik nie istnieje :)

Poniżej screenGif z przykładem:
![Animation2](https://user-images.githubusercontent.com/30685349/117351913-94dd3680-aeae-11eb-9154-81fb590a84e8.gif)

**Comment by pwarchol** [comment]
@kanlukasz tak, masz rację gdzieś mi umknął ten warunek.
Poprawka już jest w repo, wyjdzie w wersji v0.3
Dzięki

**Comment by pwarchol** [comment]
@kanlukasz v0.3.0 opublikowana.

**Comment by kanlukasz** [comment]
działa teraz ok 👍
