### ISSUE TITLE
Linking does not work if we set "editor.links" to false

### ISSUE THREAD

**Issue by kanlukasz** [pwarchol/vscode-php-file-link#4]
W momencie gdy w ustawieniach dodasz `"editor.links": false,` żaden link nie działa. Jak zmienię na `true` to wszystko działa.

Opcja `editor.links` definiuje tylko warstwę wizualną (tylko czy widać podkreślenie czy nie) więc czy wtyczka nie powinna nadal działać niezależnie od ustawienia tej opcji?
Tak to przynajmniej funkcjonuje natywnie w VSCode w przypadku plików HTML 

Co o tym sądzisz?

ps. sorry za brak Pull Requestów do repo, ale słabo ogarniam JS/TS; siedzę głównie w PHP 😢 

ps2. screenGIF do podglądu jak to działa oryginalnie w HTML:
![Animation23](https://user-images.githubusercontent.com/30685349/117402611-05b03d00-af07-11eb-877d-032892d39b7c.gif)

**Comment by pwarchol** [comment]
@kanlukasz testowałeś to na czystym vscode? Sprawdziłem na moim i czystym środowisku i po ustawieniu `editor.links: false` nie mogłem przejść z html do css.
Korzystam z [DocumentLinkProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentLinkProvider) które musi być blokowane po ustawieniu tej opcji na false.

**Comment by kanlukasz** [comment]
Faktycznie, przepraszam Cię, testowałem na moim i chyba inny plugin to spowodował, bo faktycznie na czystej jest tak jak mówisz.
W takim razie zamykam temat
